# Page settings

baseURL = "/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
# googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Tom Eklöf"
    description = "Twenty+ years of experience in the field"


    primaryColor = "#c5a07a"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Tom"
        tagline = "Site Reliability Engineer"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "Remote"

        # [[params.contact.list]]
        # icon = "fas fa-phone-square"
        # url = "tel:#"
        # text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "tom@linux-konsult.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "linux-konsult.com"







    [params.skills]
        enable = true
        [[params.skills.list]]
        # title = "Technical"
        [[params.skills.list.items]]
        details = "AWS"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "DevOps/SecOps"
        [[params.skills.list.items]]
        details = "CI/CD"
        [[params.skills.list.items]]
        details = "Docker"
        [[params.skills.list.items]]
        details = "Terraform"
        [[params.skills.list.items]]
        details = "CloudFormation"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Kubernetes"
        [[params.skills.list.items]]
        details = "Linux"
        [[params.skills.list.items]]
        details = "Observability"
        [[params.skills.list.items]]
        details = "GitLab"
  








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Architecting on AWS"
        university = "Amazon, Sweden"
        dates = "2017.06"
        [[params.education.list]]
        degree = "GitHub, Train the Trainer"
        university = "GitHub, Sweden"
        dates = "2016.06"
        [[params.education.list]]
        degree = "Solaris 9 System Administration"
        university = "Skillsoft, Remote"
        dates = "2007.06"
        [[params.education.list]]
        degree = "Cisco CCNA"
        university = "Stockholm, Sweden"
        dates = "2003.06"
        [[params.education.list]]
        degree = "Introduction to Internetworking"
        university = "Learningtree, Sweden"
        dates = "2001.06"
        [[params.education.list]]
        degree = "ITIL v3 Foundation"
        university = "Stockholm"
        dates = ""
        [[params.education.list]]
        degree = ""
        university = ""
        dates = ""








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Swedish"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Gardening"
        [[params.interests.list]]
        name = "Home automation"
        [[params.interests.list]]
        name = "Cryptocurrencies"
   








    [params.summary]
        enable = true
        text = """I work as a Tech Lead in a newly formed SRE team. Our group build a cloud based backend for autonomous semitrucks.

Experience in the Autonomous Semitruck field. where I have been involved in the development of AWS infrastructure for the cloud backend and improving observability and security for several microservices.
"""








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Site Reliability Engineer"
        dates = "2021.10 -  Present"
        company = "Scania R&D"
        details = """Tech lead, transition observability to a cloud native stack."""
        [[params.experience.list.items]]
        details = "Envangelise SLO and help teams implement observability"
        [[params.experience.list.items]]
        details = "70% cost optimiziation of Kubernetes klusters with spot instance pricing"
        [[params.experience.list.items]]
        details = "Showcased Grafana with augmented SVG dashboard"
        [[params.experience.list.items]]
        details = "Transitioned GitLab CI runners to kubernetes"

        [[params.experience.list]]
        title = "Platform engineer"
        dates = "2010.12 - 2021.10"
        company = "Scania R&D"
        details = ""
        [[params.experience.list.items]]
        details = "Minimize human labor efforts to automatically detect secrets committed in code"
        [[params.experience.list.items]]
        details = "Define metrics standards to unify each teams SLIs"
        [[params.experience.list.items]]
        details = "Fargate ECS"
        [[params.experience.list.items]]
        details = "Improve observability with unified cross-account Cloudwatch metrics"
        [[params.experience.list.items]]
        details = "Make prometheus/kafka metrics available in CloudWatch with OpenTelemetry"
        [[params.experience.list.items]]
        details = "Serverless framework (Python) api to emit release related metrics"
        [[params.experience.list.items]]
        details = "Improve reusable GitLab CI pipeline boilerplates"
        [[params.experience.list.items]]
        details = "Renovate Bot, detect and create automatic library/container supply chain updates"
        [[params.experience.list.items]]
        details = "Maintain CloudFormation code to streamline infrastructure such as WAFs"

        [[params.experience.list]]
        title = "Development engineer"
        dates = "2019.01 - 2020.12"
        company = "Scania R&D"
        details = "Build cloud backend services for Scanias Autonomous vehicles."
        [[params.experience.list.items]]
        details = "Security lead"
        [[params.experience.list.items]]
        details = "Cloud account owner"
        [[params.experience.list.items]]
        details = "GitLab CI"
        [[params.experience.list.items]]
        details = "Data Dog monitoring"
        [[params.experience.list.items]]
        details = "Kinesis"
        [[params.experience.list.items]]
        details = "Wrote Python services with the Serverless Framework"
        [[params.experience.list.items]]
        details = "Wrote reusable CI pipeline boilerplates"
        [[params.experience.list.items]]
        details = "Managed Nexus package repository infrastructure"

        [[params.experience.list]]
        title = "Cloud Architect/Engineer"
        dates = "2018.01 - 2019.01"
        company = "Scania IT"
        details = "Facilitate adoption to AWS greenfield and Data Center extension accounts for Scanias AWS accounts"
        [[params.experience.list.items]]
        details = "Terraform"
        [[params.experience.list.items]]
        details = "Ansible"
        [[params.experience.list.items]]
        details = "GitLab configuration & pipeline setup, mainly with Terraform and Ansible"
        [[params.experience.list.items]]
        details = "Control blast radius with cross-account role assume strategies"
        [[params.experience.list.items]]
        details = "Lambda automation (python)"
        [[params.experience.list.items]]
        details = "Coach an SAP DevOps technician to build capability for a hands off deployment of a SAP system with a single GIT commit. This is to be used within their business unit as a good example of the benefits of automation."
        [[params.experience.list.items]]
        details = "\"Sell\" cloud benefits to developers such as using and rotating secrets, with Java code examples so that secrets don't have to be persisted to disk"


        [[params.experience.list]]
        title = "Technical Specialist Linux Server"
        dates = "2015.01 - 2017.12"
        company = "Scania IT"
        details = ""
        [[params.experience.list.items]]
        details = "Plan, improve & lifecycle 100+ RHEV hypervisors and 1400+ VMs"
        [[params.experience.list.items]]
        details = "Python scripting to automate storage migrations et cetera utilizing (mostly) RHEV APIs"
        [[params.experience.list.items]]
        details = "Handle management & provisioning automation for virtual machines"
        [[params.experience.list.items]]
        details = "Automate & configure with Ansible. Also educate Operations on best practices for automation"
        [[params.experience.list.items]]
        details = "Set up routines, RunDeck & Ansible automatic security patching solution"
        [[params.experience.list.items]]
        details = "Troubleshooted performance of Java/Tomcat/JBoss applications"

        [[params.experience.list]]
        title = "Solutions Architect"
        dates = "2014.01 - 2015.01"
        company = "RG19"
        [[params.experience.list.items]]
        details = "Service design, upgrade & management of UNIX/Linux related software"
        [[params.experience.list.items]]
        details = "Investigate application interconnections with tcpdump + Wireshark"
        [[params.experience.list.items]]
        details = "IBM AIX process memory management"
        [[params.experience.list.items]]
        details = "Aptean Order- and Warehouse systems"
        [[params.experience.list.items]]
        details = "Java/Tomcat/JBoss/WebSphere performance troubleshooting"
        [[params.experience.list.items]]
        details = "Measure and probe Web site performance with selenium"
        [[params.experience.list.items]]
        details = "Application wide system probing & documentation"
        [[params.experience.list.items]]
        details = "Application monitoring   "

        [[params.experience.list]]
        title = "System Administrator"
        dates = "2011.01 - 2014.01"
        company = "Mogul Services"
        [[params.experience.list.items]]
        details = "Migrated, OS/Software monitoring & hardening the Swedish Government public Web site (sweden.gov.se & regeringen.se)"
        [[params.experience.list.items]]
        details = "Mitigated a DDOS attack from the Anonymous group on the government of Swedens website , regeringen.se"
        [[params.experience.list.items]]
        details = "Set up scripting, system administration and automation for Sveriges Television (Sweden's national TV station) websites www.svt.se and svtplay.se"
        [[params.experience.list.items]]
        details = "Setup of a new Escenic / Tomcat environment for Sveriges Television"
        [[params.experience.list.items]]
        details = "Automate operational tasks in RunDeck"
        [[params.experience.list.items]]
        details = "Stingray Load Balancers; traffic scripting etc."
        [[params.experience.list.items]]
        details = "Various Nagios / OP5 plugin scripting"
        [[params.experience.list.items]]
        details = "VMWare ESXi + Netapp cluster management"
        [[params.experience.list.items]]
        details = "Percona MySQL"
        [[params.experience.list.items]]
        details = "Apache httpd management"

        [[params.experience.list]]
        title = "Java Application Technician"
        dates = "2008.01 - 2011.01"
        company = "Memnon Network Applications"
        [[params.experience.list.items]]
        details = "Application monitoring & troubleshooting in the Operation Environment Apport.net"
        [[params.experience.list.items]]
        details = "Automate deployments in a Jenkins/Hudson CD pipeline"
        [[params.experience.list.items]]
        details = "Compose Operations- & Incident Reports"
        [[params.experience.list.items]]
        details = "Analyze Java Application Errors & produce bug reports"
        [[params.experience.list.items]]
        details = "Tweak/optimize/monitor java 1.5 Garbage Collection"
        [[params.experience.list.items]]
        details = "Create Test & deployment environments for the JBoss application Apport.net"
        [[params.experience.list.items]]
        details = "Deploy internal infrastructure such as SVN, AD-connected freeradius et cetera"
        [[params.experience.list.items]]
        details = "Compose various Bash & Perl scripts (deploy & monitoring scripts mainly)"
        [[params.experience.list.items]]
        details = "Java JMX performance instrumentation"
        [[params.experience.list.items]]
        details = "Setup of redundant firewalls & redundant apache servers/load balancers"
        [[params.experience.list.items]]
        details = "Migrate Apport.net from Solaris to Linux"
        [[params.experience.list.items]]
        details = "Compose System documentation templates"
        [[params.experience.list.items]]
        details = "Set up of MySQL slave servers"
        [[params.experience.list.items]]
        details = "Produce Standard work Procedures"


        [[params.experience.list]]
        title = "Unix Coach"
        dates = "2008.01 - 2008.01"
        company = "Elan IT"
        [[params.experience.list.items]]
        details = "SLA responsible for the Ericsson R&D Service Desk"
        [[params.experience.list.items]]
        details = "Coaching of R&D Service Desk agents, backoffice & mail admins (approx. 20 ppl)"
        [[params.experience.list.items]]
        details = "Tactical Incident Management / Incident Escalation"
        [[params.experience.list.items]]
        details = "Scripting in tcsh, bash & perl"
        [[params.experience.list.items]]
        details = "Evaluate candidating agents technical proficiency"


        [[params.experience.list]]
        title = "Unix Service Desk Agent"
        dates = "2006.01 - 2007.01"
        company = "Poolia IT"
        [[params.experience.list.items]]
        details = "Support Ericsson developers with their Linux/Unix development environment"
 

        [[params.experience.list]]
        title = "Service Desk Agent"
        dates = "2004.01 - 2005.01"
        company = "HP Ireland"
        [[params.experience.list.items]]
        details = "2nd line support analyst"
        

        [[params.experience.list]]
        title = "System Administrator"
        dates = "2000.06 - 2004.01"
        company = "ISD Datasystem"
        [[params.experience.list.items]]
        details = "Systems administration (NetBSD, Red Hat Linux, IRIX & Windows)"
        [[params.experience.list.items]]
        details = "Installation of various server systems such as backup systems, email systems et cetera"



    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/silverfisk"
        title = "silverfisk"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/tomeklof"
        title = "tomeklof"
        # [[params.social.list]]
        # icon = "fab fa-twitter-square"
        # url = "//twitter.com/username"
        # title = "@username"





